name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY_IMAGE: ${{ vars.DOCKERHUB_USER }}/valkey-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        id: meta
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          export IMAGE_TAG=${{ steps.meta.outputs.version }}
          envsubst < Dockerfile.tmpl > Dockerfile
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
          push: true
